apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-api-certs-local-cluster
  namespace: default
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
  generation: 1
spec:
  disabled: false
  remediationAction: enforce
  severity: low
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-api-certs-local-cluster
        spec:
          namespaceSelector:
            include:
              - kube-system
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: bitnami.com/v1alpha1
                kind: SealedSecret
                metadata:
                  name: api-certs
                  namespace: openshift-ingress
                  annotations:
                    sealedsecrets.bitnami.com/cluster-wide: "true"
                  creationTimestamp:
                spec:
                  encryptedData:
                    tls.crt: AgBw9nZygXNNMJW660TIgAn7Yj3oEcrVwNA/FjXrh28IcueVJ1V3MZH7bNrD0T6fX4UD4GtxOT74jfXtNcs0YTiOUj7f3Fy18TK3P5CqpfobenwV4vsaom/7gxX7RFwrvBbJFlkL+RB8wKCeJ18vWELiYdF7enG0/OAaXV7UW/ULp8RPMqQkJpxwBHFVDw6ba670nCI1N4OMcqEK4JsHdzQu1QtBFMNsPk1O2500W9l9lLEnDDueXS/5X1EzeTTuO0ooDig7y4caDawGbOQSEUYf/1y8uehWl8lq/wwHWeySfBV2GzpXFBH5QzVJRw/TV5K9SVdP+ois0fKiXkwQolZ8DHUCN3mdD9IpUUrfu08BnPOLvNK0ujN0C68JPFQByauTMQ54W5lqFDngemhjfnJbRWQm/Y+W0o+PR7XTZDL5VAn4aHTa55QVDIQMKBopxRcrdGyw0GuMYGPMoGNvI18s5+F9bkn04+Fa9mrNkPZly3XTxBuOnkuOc1hEALbshH0Ews55/6UaWdtvXasntxZbX69xoiW+era7WWkLrAQA/ttxsBXiFX2vE6wKPqYpL2P4EFN74rtQtrbYxnOyOodkevrIhhYRNo/qyqkArcnrKfUggwvV2BpwaqrwN/+2NL3zyzYvmC2c49LsE3iDRnarA2qTRgCbm9fCs6/GLHa0ZZlzH0xGe53YYQnnU8me32F4USkfobOLe+XoVm/07rB2DaFOpQTMBXSuGeV/GpWANU+bvzaHEpOaewqOQgnIw2esm38Skfe1m+xLhXgTeZHoNHnytVxfKFA9S6fgq5gtrZpBPkuMtlITlApNrXNi6osUils2xA/uunvc69xK9NLhzb+zitIl8WI38cqbzxaKe/jWY/6CvWv+hYjbecwX4Bd+e6WVkg9z2g+kDHtLN6KCGt1eQ0mQNBD4oSzq1X86zPOVIM6Ckmz4TYl6ScPPO0FHv/Be8x6RxMj5qnPtRjkjAxStQuSIV9rXN3u0YP1EE2T70J1rQsOUBRGrF7pSXdOPhyxvY9Xxln37Uoy+atwaoIpx4lVU3JVW5XdEl0zfNQ/VGRpNz9ueXG/mFhbQ1OSs/J5dSWAhuR2EgDYj0jElZ/4Nsxl2iAbfRwTCFGJ/Ali1sYE1oaZjUn6xCJFubq7xL7efQf58CoreIkKdD6eDfymbXnqS/P0eWV/oNHArJZvmzWb5Nz18yVW3dxYknwPCm4YdSnYy6c6shKU/lT5rrRzyS6rgrug1yuHyXHFDd+0TjiooyLh7WtT5AIyP75U9gViK4pspNE8kheAzkr2dTxJ7yQJZTAR8oPcPpfIZF5HjCu0jK6JqHsEP5M9t12+MmH6J8sw24qlYLMui/He64aTR64nebBKtHAoMNDGhELM7qJDJlxGwevtHMgPIFmUYj9kIJfAGvSAzod2spIJg1lcEpA08iTAOZLgW1dg8PWgpLEXatagRm09MMIZcT0+tJSE5LZ1AIaYVlWknt1IUU/Qq/cLXtJl+obf5E4HFnyKweo/BWmc4hzFI6trs8pxNfW5pKqrZSqvnCDrUkVPEVtSDktYG3LpI4fDleHvMp+2zAWY7vXWS2V2N9c2m9Ay3hd5Nx8KOZrv7oKOPnhDLiT3eKC8PwPpeUmFmb202kMGvAX0k3b2QKDLh1TtMQB49SbGGsQ7dLdNku5FKVJzC8R2CqyBL9uiHrqyKZ81XgBaP4feoqyPR9Drnxqvjvy9A//i9PPIE8GGdsWzDNN+FmCt1Y5q1zD3FVtPBV/HHMcWiOLpLMtpIaajdspDcpjx8P/9pdhIojePjNvXBdKOJuSTOA2p938jeBa2PDN/gl/0Ag7I+02HO6jNDRAYIy5c0tuTkgNP8JSAPEW1MFbu6Z9Xu0HdCwwWWxNIS5NlTLtoT4F4lGsiLOMSPWQ1MR+K/Gb8DDV2geETe5W3f40C7dAAssPE9JQyDqim+LY8CRRrTzCek85uhvauX/Q6foloAhbIKTr7oMtX5SDzAnsmCZ6uCRh4Gn6YeKytDDBRwHlb9IhQ3cbF/HUP5mQzv53v45UOywFx5JEkEyGe+N2BBFxGeJ9lsMLvuzatmn4k81eCKfqJb+gbfF1HnCgC31hk1l/ri1D4X3BULcSx0oP4K4f9h2qytH69UI+BBIoGA7cEjuij+Wq9XUm2sXw1RO2d2Q8vZIR8DfBPq6ymLvImt0MNgPKPwmcdX3jb3PxigzSUhlrXNopX2Ye4E7fcv2qZETZ82wzAypcpn9roF8F3C0ETCznG5zbOY/OU0F2IyRygLZ1OQAtj0VFEGU/804xBqY96w5dkT6inffsWRhfI1cztbaE352ldjiBV3xSFYgtsLuJoIgGuteewWjmy93HVkdvvxtlgKIGbZ9b3eHxAXxAFr0SKyfGLkWL+K/8Le9exab0yur9N8qQeADQL/1wU4R3/mawoUJ00Y5jV7M0JQ1rz8RiYS7mZmItNNgEb0NTE2Y739NILJ5oYNbeZ1x+z4orkA79/NwMAeRgmBuiH4rjX6jyw4PtDMvXq7sD2uN1xsu4YK3brK8oEEBICyqf1hoEmlHuTgozRzka35FSpiWplkEGqj4rIXgN25gVoM8shlVRn6Pa0ukzjdjvJYN+Hr57uiqP8Qpok2NiWDsCMpbmjP2Nfj0EaPYXeTsn+ulvgr0eU9e9yXFQo48NOF8Pu+/aLOjHXldha4eyNKJVXeyFRy1NKsDATpDOuVKkTjgrbFVQmcJ4mk5WPhhfJYHfRGHtbrWspBPHWY5dqAge4atF8wwBbOcbG/+nkA4I63SvWVwTX9xzcEFOL3jCoCtcg9Xh9XJQ8s0dcJKPwKab6YlBPH8MNIKVEyB5Pumswi4hosbqDlo94G9PsRrkzxrXOIg7rXI2irCXrv3pADIb48EGNDbKsmn8Y7W479YiqUaYtqykMd61uMqMB5Psza4dJyh/1fJDhKYWUHOFDL8W+W7zhrxzMsEtuNbLSjaEaQHcRB2XJ8Ep2MP7Q1rRIVqHBm3j7W0Ruye8ZyW7XqZ8KPguu80lfBQezVKjNU4+ObhlF+k+xUsTSLs6MtMU23Fg77UYEmvjnSKmLbTP1+A2tZbAV+6P3ySCmxydyE7d1E916a/45E643Rkl8OJlghSrGtUekPy6JiVPslH8dji8mPrDOLEbZMudLo9xdazuAFVvctsLzxV2Woj154eqk4D+gZnEkYemyIsY4rONeJhwPvSxM//Wccz6DbzWzny5hlASGwpBmsVUn0nBBQ3nzjE1a9mqX3xrrvm/LJCl2KOwabIvhjA1ckUjI+Qcn9TGGvj1CDNdbwG+2vQzgVfxFnRxX7N840pGnLgCwCbOnUF0FX+ThCqb2QkeIINxxqsKk9hZFE+X/5wBJGK/RuwfrSF+2s56s2+XVz4JKLfWdEV6HhZmZ5RBS9ECW2nG8LM1/ZdW/agWusyKAT1hmo5TEeWfmv6V4ZqYpKs2+g4gcoAQTJW5fAW3JJ1PX+5fKKUtJnnr27NEO11oRlNwEHFMYmxaYNuZRATGTEHueaKsXJk56PnvBsc/QnIHjIGbH5PMzHPsmkfb9CsFRv0VZheCm9sNmw+tpPpCj4s2Z3lHB0e7xTyvIp+p84h0GUDiA0+jwa8F3GsS14NsQoBggu2JsEj+YkwLgXmPGKGtfzeRDjlZhgnGhxy7tdIjz18tJK+r/e67Z1zO82gvwOKGVaaQTP+XJpInMMayEmpT6PlWL5bYgviKD97hNtmJ+WXDrHtDT7fmKsKg8WLTf+KVRaizSEEwqySdlapSMDr9o+KpAIRRY7B0TZ3jq+euX+PH9oIEYmuHH8Ulil6yVl9QkbE9VZ2vyFM3GW03Y0aQwl8oGBTvHicNL0iXy5N3jHIC2hhLHIgQbuzr9icZppXjAsNHngRHmJFldOgarvTPyo+MCQVjcGfD3gl63uZC/2dMchuTaD0gJYT5zwiX8J5dnUyj9v6886nEYKUn5WIy3M14RArfu9zWAKRPNO2AjpQtBcmgk+YvjEEZK0GwMHSlJHD9ysPQCeB5Hzt98nPkHWsfrCXhpXFZwxE/xeMxwyXd/rpLZ1wfqniGQzSQ+dPWTd+UEBzfqLZxGyn2SrFh0Yy3gFBaCwIDy2iBEYxpjFJaRMT1LXL9Dsjc0DYd84nLjjiBcVM8B7YsWtGr6CSRmdH0JBLtNKp1/Sn9LenEiQxz9Y6iwPQDizOVDFtbvoJXfnvKb1/jieIq0N59EIf+xu1PUfJSaDgfSWoSd5G6HmNJWeGnTuiY+lk9Q8VFlMGtGw0/EqTLsvDiM7W3gRVN6qHrghSklwEiPa5QpCdmkYpowDYMsOm6BGQcfnHFaQVtGrEVd0Fp1YCiSlvcUXCOqyFNlp0uB8jFW79bHNuy7DC2jq03tWJneATmC7c6mG0qAV/eofd60d/01O4RX934249SsyqlRc2fdyKPaMyoopCcyyGE9hlfifW+FpWTurIqWU32hvivdJDI/fFYPsWkC6Wjqkiq1b3RFSsIBfXWvq8OPLXFGM22CjAjf7k8/QQMTucv4MQ1ttd5ZelBxxdfGb0fAwgal+zFLngjkHgOFJW+whh27LBynqb2J1F8/wEMlP+5xoRzHfwjZv9bQbkvKTDC48dZP5Mw1JjODgp6P9NGjVd+X0DuF264rFDVBPtp0F3vef8Y47O0zn/KcLxqx+VNW8xOk5Bgma9EchjxR6CWm8ALSsE/1+xMubUTvbI5j4slOXsizxvtd8XzSs2940xhHAiEDyWtfNwdkO5kANeJRf++ysxTXjTWzoET4Z++J2GzAD7MqEqF8gNZzqmWQ7n0GIpuI+6bG63X0DiXAy7LnDinirOIoMN3IvxpRdLEEAUSlfoTWYxh8T8ZItqp0fo2xdaK47FU04T81zMrpGABmKlWxV77rMKqd2AKNJ0YaibKX+3zJ/K/IRILMEZNavAfsKNfKC57jrMinEB71Xl9eujzZ/6OHG/QlGqn6WVEuvp2nRZUpmvt9o9i1vS5+w/vLg7D+jhXICFGTGtIuvEpiI8IF4HmMez+3/W0rKKlVDhD5APpfC3VGsrmSjss5wvSw/7ewiSObpx3AS2jg3LISiX3OBDzamMmn3iZ9KPhzS4OCvffQqyjvlMpoPB4yyKJlzXfHg2fgj/eY1PqB5c27t+uqrAPqORzvHLumbXcKOtTWolsmBb1GH4Q6a5RGTLNl5PLv7VqqQQ4bZ25vH7I73mYcpHyrwAA7GSd/syY2e6H5oYg6+MigjOhdmrm3HVasdNauE1yAQAHg+WG6CIgQSHjQjIP6cWnSsDdRMNZbVish4Sqm+9OOmpQUHILpibkHqfTiR/EN4+WVh3NJuRcIdnKDZBj+kjgH75g4ivtKg5UrDwXoIhl39+cI+rLoEr5jzl2B+LolRQOSY5IZrvGcyHEeY1GXGB+4MCao0Vbf5649PsvBtozU5oq16a66mvKe8eQFu2Nc9KfSUmIFeUUZ1Q3iW7G9HUJtbjJ0ulyLlNi6v7guwThnFwZHLTpzomhMkpUugwoaeOxgvQ/fF1tbrAmb80mq8jjXczzThJvchMfKKLHsoSzVv6MC53U57bcTOLF0ZfTagYzFifvwwLbVpQlerTVFCAy8hGMCj7toBt4T6wd4WzoZ2OJV+pSgLwIKBmJ71FoPlFsGACQrhpfYr/v9mawQRlq/Er3lwCtIvblGVXpVCI2hGdo1d+Eg+rmprIbGSo3xzjaH2aQ225hXRkWXZGaf7t20en3oufVMc+/pSn4NSkKyxEjuCff9NzKctChHfVde49aNgRZmvqwcPPEfj1dAP/n/XpHAEJFU8Ekv9NxKqv2sX0OcoOaNdSxuoJm9djrPCorHKnc2STbMEyxgWbTxFZQnueMF/4mU0lHXjoeuaVvPvfkK1/5ELc53NvLi5tFp8ctGhUcI2r0tb0OZdNA+1o+X1jAeJlK06DR1ZnwxIRhBkykfXs9JLLH159ayUctjabJmOpAImKZ/2WRs+8R/X+K6Ce+nybrI8RVvxq6yr9m9hftLh1FHuOT5xk4GxQ2z0zO2wnAwXzxijO3LUpnnOxWMv4wuLog+0So2o6kUF7b0Pz++luAG7UWR7Tog4jKjf8YfLaI9NndLGYTC49ZFPKs+QVTQcOdHnpk5WaTN7r60cD9IWXXpwx2ODFzdqb7eqdZf4X7XQ+vME5zdAPgEGAHKk4YNx/O+KCN0hZlDjroeUfIS9pGz0sNLjNRb1nvlnGymo2SclKI6ReIpZhOS/9iHyjPhFepGkp4jkAtIDnSodjyKPV2HFLfwDbyqXECMFdw==
                    tls.key: AgC7fD73RcUYo5EdvnvYYzppJsjk0c8OoJjKF5M+q5V6SWx0jQ0WBGGJaFNG15UDfxV46nDqDkGhp7lAmJhZIPhj5m25VMEZD7TTOHtOhE2ptkUMcb6AOICSWdX6qpNxT+GMUu3nyO3WfJELNI/pNbXhXU4JfuARJZQq+RieiUIjcNicp9N1Bs8UYrDBc0ATM4w5lEbfwvG36kEk8m3vb2L5ZqP1g6J1PZitoAlDHkalbzTvCX+s0Mh6qBEXjNQK66FbUXJ/UoMfPCZLC2zUdvC2NGJVkZWteQjy+LE3gEWvkeULkDJOFR1RB5Ww6R2qhB8/wmoldPBx7OaezzM6/uSTfl3YHcyl2/SXfxxiR5EOMm7cvmhuTxfynyIryA6gXF8rrzUNBff/U8N7KRrR64ImM02rJlsBSJq6+YdIG5H2s448SIJMqMp2IAlN2vSjNK6ef6Tk06c04Ik9obTm0CV15qSxMhV5x1ECrI3zgmC/5EiEeX3x8LK4Rqu76QP+/cK1Fdc82NI72xCHWevhBIcCTDGpSbRgP7gsu0B9So6Yi0jxnytXILR/Cm7ifwQkUpKWe6HDUDY3ey2abtNya2b7dZDM1dkUnt/60kCMlEu63DWCLJKaBaozZbmO/AnPbJ4fLwk7hUohlAy3n5lkR1EfubZwTdm9mM8T9J8aNxQVGTUeaFX3wFvtlj6v43b4cF8gTjveBd8wg/MxBjQF8kZVzsVBdsORs3PxUnexJVhlTj13VRbG3Yo++fSb/yND5ijTB0m3BnBdMIDe+kZ+3JrrVxQgSaMRTYXlE0Y8SySlHUbdXvrHldIm+WbLun2aC9Qi5gDMAmQM3eC4h/GXZ7oWV2ayw1GJP787tSZ2+rsZkuIUoVL+6Njf8SnWfGSXGFWVTwMMNbFzcsUGm4GnnSxwP7pxnpBtbssMXJbJ+hvOVlqO+LOqZlifLlkgcfxrZdGqAEsT/vfip/Y4DoJzps5Ozl5Jj/CV1pVv/Qr2b+AKYf69
                  template:
                    metadata:
                      name: api-certs
                      namespace: openshift-ingress
                      annotations:
                        sealedsecrets.bitnami.com/cluster-wide: "true"
                      creationTimestamp:
                    type: kubernetes.io/tls

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-api-config-local-cluster
        spec:
          namespaceSelector:
            include:
              - kube-system
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: APIServer
                metadata:
                  annotations:
                    include.release.openshift.io/ibm-cloud-managed: "true"
                    include.release.openshift.io/self-managed-high-availability: "true"
                    include.release.openshift.io/single-node-developer: "true"
                    oauth-apiserver.openshift.io/secure-token-storage: "true"
                    release.openshift.io/create-only: "true"
                  name: cluster
                spec:
                  audit:
                    profile: Default
                  servingCerts:
                    namedCertificates:
                    - names:
                      - api.hub-lab.digitaldovey.net
                      servingCertificate:
                        name: api-certs                  
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: policy-api-certs-local-cluster-placement
  namespace: default
spec:
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - local-cluster
  clusterConditions: []
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policy-api-certs-local-cluster-placement-binding
  namespace: default
placementRef:
  name: policy-api-certs-local-cluster-placement
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: policy-api-certs-local-cluster
    apiGroup: policy.open-cluster-management.io
    kind: Policy
