apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - sealed-secrets
---
apiVersion: v1                      
kind: Namespace
metadata:
  name: hbitnami-labsgithubio-sealed-secrets-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: hbitnami-labsgithubio-sealed-secrets
  namespace: hbitnami-labsgithubio-sealed-secrets-ns
spec:
  type: HelmRepo
  pathname: 'https://bitnami-labs.github.io/sealed-secrets'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
  labels:
    app: sealed-secrets
  name: sealed-secrets-subscription-1
  namespace: kube-system
spec:
  channel: hbitnami-labsgithubio-sealed-secrets-ns/hbitnami-labsgithubio-sealed-secrets
  name: sealed-secrets
  packageOverrides:
  - packageName: sealed-secrets
    packageAlias: sealed-secrets
  packageFilter:
    version: "2.8.0"
  placement:
    placementRef:
      kind: PlacementRule
      name: sealed-secrets-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: sealed-secrets
  name: sealed-secrets-placement-1
  namespace: kube-system
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'
