kind: Kustomization

namespace: default

#bases:
#  - base

resources:
# - policy-github-oauth.yaml
# - policy-cluster-admin-role.yaml
# - Certs/policy-api-certs.yaml  
- Certs/policy-router-certs.yaml   
