kind: Kustomization

namespace: default

#bases:
#  - base

resources:
 - Auth/policy-github-oauth.yaml
 - Auth/policy-cluster-admin-role.yaml
# - Certs/policy-api-certs.yaml  
 - Certs/policy-router-certs.yaml   
